name: phpcs

on:
  pull_request:
    branches:
      - "master"
    paths:
      - '**.php'

  push:
    branches:
      - "master"
    paths:
      - '**.php'

jobs:
    phpcs:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
              with:
                token: ${{ secrets.PAT }}
                ref: ${{ github.head_ref }}

            - name: check php version
              run: php -v

            - name: download phpcs
              run: wget -O phpcs.phar https://cs.symfony.com/download/php-cs-fixer-v2.phar

            - name: make phpcs executable
              run: chmod +x phpcs.phar

            - name: apply coding style
              run: php phpcs.phar fix

            - name: remove phpcs
              run: rm -f phpcs.phar

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  ref: ${{ github.head_ref }}
                  commit_message: 'phpcs: apply coding style'
                  commit_options: '--no-verify --signoff'
